# Generated by Django 3.2.7 on 2022-12-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('designation', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
            ],
            options={
                'verbose_name': 'Entreprise',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('designation', models.CharField(max_length=255, verbose_name='Nom du site')),
                ('id_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('designation', models.CharField(max_length=255, verbose_name='Nom de la zone')),
                ('id_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('code_nfc', models.CharField(max_length=255, verbose_name='code NFC')),
                ('designation', models.CharField(max_length=255, verbose_name='Nom du TAG')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordre')),
                ('observation', models.CharField(max_length=255, verbose_name='Observation')),
                ('id_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TagDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('memo_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lien de la memo')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description_anomaly', models.TextField(blank=True, null=True, verbose_name='Anomalie')),
                ('is_checked', models.BooleanField(default=False, verbose_name='tag visité')),
                ('id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tagheader', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag détail',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créé')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modifié')),
                ('designation', models.CharField(max_length=255, verbose_name="Nom de l'employée")),
                ('id_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
            options={
                'verbose_name': 'Employée',
            },
        ),
    ]
